### ISSUE TITLE
Use Includeonly to Separate Chapters

### ISSUE THREAD

**Issue by dellpit** [BigThonkers/Latex-Mitschriebe-Semester-3#13]
Remember to set root document or whatever.

**Comment by benjaminbutton13659** [comment]
Included ,,\include`` for chapters.
Had to use TeXstudio's Detect Automatically option.
Cannot set root document with several different Tex root documents (Ex/Theo) in one Folder. 
Automatic detection works perfectly fine i can even compile the single chapter documents without any problems and without extension packages.

**Comment by dellpit** [comment]
very cool
