### ISSUE TITLE
V.3.4 Fix lowercase and capital Ws; Rayliegh-Jeans

### ISSUE THREAD

**Issue by dellpit** [BigThonkers/Latex-Mitschriebe-Semester-3#14]
1) Just look at his script.  The \bar ones are all capital it seems, some of the others are lowercase.

2) It's not Rayligh-Deans.

**Comment by benjaminbutton13659** [comment]
where are the upper/lower case typos ?

Fixed Dean

**Comment by dellpit** [comment]
\ol{w} should be \ol{W} according to the professor's script.  I can take a look again later, but a few of the ones that we wrote down as W should be w.  It's just that part in chapter 5, though.

**Comment by benjaminbutton13659** [comment]
Done
