### ISSUE TITLE
Compiling Errors

### ISSUE THREAD

**Issue by benjaminbutton13659** [BigThonkers/Latex-Mitschriebe-Semester-3#8]
There are some issues in both scripts that i can`t resolve:
(You can find them in the Log output of your compiler)

1.
destination with the same identifier ... has already been used, duplicate ignored <to be read again>
normally this has to do with multiple identical chapter/section titles

2.
Font shape ... not available(Font) Font shape ... tried instead
this has to do with small or big font sizes for math-mode that are sometimes required
(sometimes one line is shown but if you comment it out it changes to another one below
i couldn`t find the error-causing line)

3.
The counter will not be printed
(only in Ex III) i cannot find the cause of this error no line is shown

**Comment by dellpit** [comment]
The second one seems to be related to how vectors are defined.  This seems to fix it, at least on my end:
```tex
\usepackage{bm}
[...]
\renewcommand{\vec}[1]{\bm{#1}}
[...]
\newcommand{\vabla}{\vec{\nabla}}```

**Comment by dellpit** [comment]
The third one seems to be related to
```tex
\begin{enumerate}[$\Rightarrow$]
```
I commented two of these out on chapter 5 and the warning disappeared. [Stackexchange on the issue.](https://tex.stackexchange.com/questions/253213/how-to-remove-the-warning-the-counter-will-not-be-printed-when-using-enumerate)
I think [this suggestion](https://tex.stackexchange.com/a/84940) might be the best fix.
